config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get "/about" => "topics#about"

  resources :topics do
    resources :comments
  end

  resources :users
  root 'topics#index'

end

app/models/category.rb
class Category < ActiveRecord::Base


  has_many :topic_categories
  has_many :topics, :through => :topic_categories
end

app/models/comment.rb
class Comment < ActiveRecord::Base


  validates_presence_of :content, :user_id
  belongs_to :topic, :counter_cache => true
  belongs_to :user

end

app/models/topic.rb
class Topic < ActiveRecord::Base

  validates_presence_of :title, :content, :user_id
  has_many :comments, :dependent => :destroy
  belongs_to :user

  has_many :topic_categories
  has_many :categories, :through => :topic_categories

end

app/models/topic_category.rb
class TopicCategory < ActiveRecord::Base


  belongs_to :topic
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  include Gravtastic
  gravtastic

  has_many :topics
  has_many :comments

  def user_display_name
    nickname || self.email.split("@").first
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :nickname
    devise_parameter_sanitizer.for(:account_update) << :nickname
    devise_parameter_sanitizer.for(:sign_up) << :bio
    devise_parameter_sanitizer.for(:account_update) << :bio
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_topic

  def create

    @comment = @topic.comments.build(comment_params)
    @comment.user = current_user

    if @comment.save
      flash[:notice] = "回覆成功"
      redirect_to topic_path(@topic)
    else
      render :template => "topics/show"
    end
  end

  protected

  def comment_params
    params.require(:comment).permit(:content)
  end

  def set_topic
    @topic = Topic.find(params[:topic_id])
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  before_action :authenticate_user!, :only => [ :new, :create, :destroy ]

  def about

  end

  def index

    if params[:cid]
      category = Category.find(params[:cid])
      @topics = category.topics
    else
      @topics = Topic.all
    end

    @q = @topics.ransack(params[:q])
    @topics = @q.result(distinct: true).page(params[:page])
  end

  def show
    @topic = Topic.find(params[:id])

    unless cookies["view-topic-#{@topic.id}"]
      cookies["view-topic-#{@topic.id}"] = "true"
      @topic.increment!(:views_count)
    end

    @comment = Comment.new
  end

  def new
    @topic = Topic.new
  end

  def create
    #@topic = current_user.topics.new(topic_params)
    @topic = Topic.new(topic_params)
    @topic.user = current_user
    if @topic.save
      flash[:notice] = "新增成功"
      redirect_to topics_path
    else
      render :action => :new
    end
  end


  protected

  def topic_params
    params.require(:topic).permit(:title, :content, :category_ids =>[ ] )
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end


  def edit
    if current_user.id == params[:id].to_i
      @user = User.find( params[:id] )
    else
      flash[:alert] = "哈哈哈！"
      redirect_to root_path
    end
  end

  def update

    @user = User.find( params[:id] )
    if @user.update( user_params )
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  protected

  def user_params
    params.require(:user).permit(:nickname, :bio)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Forum101</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="myNav">
    <div class="container">
      <div class="row">
        <nav class="navbar navbar-default" role="navigation">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </button>
            <%= link_to 'Forum Mini-Project', root_path, :class => "navbar-brand" %>
          </div>
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse navbar-ex1-collapse">
            <ul class="nav navbar-nav navbar-right">
              <% if current_user %>
              <li class="dropdown">
                <a href="" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.user_display_name %> <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><%= link_to '編輯個人資料', edit_user_path(current_user.id) %></li>
                  <li><%= link_to '修改密碼', edit_registration_path(:user) %></li>
                </ul>
              </li>
              <li><%= link_to '登出', destroy_user_session_path, :method => :delete %></li>
              <% else %>
              <li><%= link_to '註冊', new_registration_path(:user) %></li>
              <li><%= link_to '登入', new_session_path(:user) %></li>
              <% end %>
            </ul>
          </div><!-- /.navbar-collapse -->
        </nav>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <% if flash[:notice] %>
      <div class="alert alert-success"><%= flash[:notice] %></div>
      <% end %>
      <% if flash[:alert] %>
      <div class="alert alert-warning"><%= flash[:alert] %></div>
      <% end %>
    </div>
  </div>
  <div class="maincontent">
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <%= yield %>
        </div>
      </div>
    </div>
  </div>


</body>
</html>

app/views/topics/about.html.erb
<h2>本站數據統計</h2>

<p>User Count: <%= User.count %></p>

<p>User : <% User.all.each do |u| %>
          <%= u.user_display_name %>
          <% end %>
</p>

<p>Total Topic : <%= Topic.count %></p>

<p>Total Comment : <%= Comment.count %></p>

app/views/topics/index.html.erb
<h2>Topic list</h2>

  <div class="group">
    <%= link_to "新增主題", new_topic_path , :class => "btn btn-primary" %>
  </div>
  <div class="clearfix"></div>
  <div class="text-right">
    <%= search_form_for @q do |f| %>

      <%= f.label :title_cont, "search title" %>
      <%= f.search_field :title_cont %>

      <%= f.submit "GO~", :class =>"btn btn-primary btn-sm" %>
    <% end %>
  </div>

  <ul class="nav nav-tabs">
    <li role="presentation"><%= link_to "All", topics_path %></li>
    <% Category.all.each do |c| %>
    <li role="presentation"><%= link_to c.name, topics_path(:cid => c.id) %></li>
    <% end %>
  </ul>


  <div class="table-responsive">
    <table class="table table-hover">
      <thead>
        <tr>
          <th> <%= sort_link(@q, :id, 'ID', default_order: :desc) %> </th>
          <th> Title </th>
          <th> User </th>
          <th> <%= sort_link(@q, :views_count, '點閱數', default_order: :desc) %> </th>
          <th> <%= sort_link(@q, :comments_count, '回覆筆數', default_order: :desc) %> </th>
          <th> <%= sort_link(@q, :updated_at, 'updated_at', default_order: :desc) %> </th>
        </tr>
      </thead>
      <tbody>
        <% @topics.each do |t| %>
        <tr>
          <td> <%= t.id %> </td>
          <td> <%= link_to t.title, topic_path(t) %> </td>
          <td>
            <%= image_tag t.user.gravatar_url, :class => "media-object", :title => t.user.user_display_name, :size =>"30", :style =>" border-radius: 50%; display:inline;" %>
            <%= link_to t.user.user_display_name, user_path(t.user_id) %>
          </td>
          <td> <%= t.views_count %> </td>
          <td> <%= t.comments_count %> </td>
          <td> <%= t.updated_at.to_formatted_s(:short)  %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>


  <div class="text-center"><%= paginate @topics %></div>

app/views/topics/new.html.erb
<div class="">
  <h2>新增Topic</h2>
    <% if @topic.errors.any? %>
      <ul>
        <% @topic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    <% end %>
  <%= form_for @topic do |f| %>
    <div class="form-group">
      <%= f.label :title, "Title" %>
      <%= f.text_field :title, :class => "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label "選擇分類：" %>
      <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) %>
    </div>
    <div class="form-group">
      <%= f.label :content, "Content" %>
      <%= f.text_area :content, :class => "form-control", :rows =>15  %>
    </div>
      <%= f.submit "submit", :class =>"btn btn-primary"  %>
  <% end %>
</div>

app/views/topics/show.html.erb
  <h2>RE: <%= @topic.title %></h2>
  <p>
    <% @topic.categories.each do |c| %>
      <%= link_to c.name, topics_path(:cid => c.id) %>
    <% end %>
  </p>
  <p><%= @topic.content %></p>

  <div class="comment-form">
    <% if @comment.errors.any? %>
      <ul>
        <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    <% end %>
    <%= form_for @comment, :url => topic_comments_path(@topic) do |f| %>
      <div class="form-group">
        <%= f.text_area :content, :class => "form-control", :placeholder => "在這裡回覆...." %>
      </div>
        <%= f.submit "submit", :class =>"btn btn-primary"  %>
    <% end %>
  </div>

  <p></p>

  <div class="comment-area">
    <% @topic.comments.each do |c| %>
    <div class="media">
      <div class="media-left">
        <a href="#">
          <%= image_tag c.user.gravatar_url, :class => "media-object", :size =>"50", :style =>" border-radius: 50%;" %>
        </a>
      </div>
      <div class="media-body">
        <h4 class="media-heading"><%= c.user.user_display_name %></h4>
        <%= simple_format c.content %>
      </div>
    </div>
    <% end %>
  </div>

app/views/users/edit.html.erb
<div class="col-md-4 col-md-offset-4">
<h2>Edit User</h2>

<%#= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f| %>

<%= form_for @user do |f| %>
  <div class="form-group">
    <%= f.label :nickname %><br />
    <%= f.text_field :nickname, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :bio %><br />
    <%= f.text_area :bio, :class => "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit "Update", :class =>"btn btn-primary"  %>
  </div>
<% end %>

<%= link_to "Back", :back, :class =>"btn btn-default"  %>
</div>

app/views/users/show.html.erb
<h2><%= @user.user_display_name %></h2>
<p><%= @user.bio %></>
<h3>Topic list</h3>
<ul>
<% @user.topics.each do |t| %>
  <li><%= link_to t.title, topic_path(t) %> at <%= t.created_at.to_s(:short) %></li>
<% end %>
</ul>

<h3>Comment list</h3>
<ul>
<% @user.comments.group(:topic_id).order("comments.id DESC").each do |c| %>

  <li><%= link_to "Re: #{c.topic.title}", topic_path(c.topic, :anchor => "comment-#{c.id}" ) %>
      at <%= c.created_at.to_s(:short) %>
  </li>

<% end %>
</ul>